# 3.promise基础

## 实例对象和函数对象

### 实例对象

- 通过构造函数new出来的
- const obj={ }

	- 这个也是实例对象,它有使用new Object( ) ,只是被隐匿了

### 函数对象

- 就是函数

	- 可以给其添加属性和方法

## error 类型

### 1 ReferenceError

- 引用的变量不存在的错误

### 2 TypeError

- 数据类型不正确的错误

### 3 RangeError

- 数据值不在其允许的范围内

### 4 SyntaxError

- 语法错误

	- 语法错误时,所有的代码不会执行

## try{  }catch( ){ }finally{ }

### try..catch需要一起出现,否则会报错

### 作用

- 在try语句块中出错的语句,会将错误抛给catch

### 不能捕获到SyntaxError错误

### catch中捕获的错误,有两个属性

- message属性

	- 错误的相关信息

- stack属性

	- 函数掉用栈记录信息

### 人为抛出异常

- throw 数据
- throw new error(参数)

## Promise对象

### 通过new Promise( )出来的对象

### 状态只能改变一次,也就是resolve( ),或者rejecet( ),如果两个同时出现,则谁先出现就是该状态

## then方法

### promise对象可以调用该方法

### 该方法可以传递两个回调函数作为参数

- 参数1:promise对象成功时会调用该回调函数
- 参数2:promise对象失败时会调用该回调函数

### 该方法会返回一个promise对象,默认为成功状态,该方法的return返回值(非promise)会作为下一次then或者catch调用时的参数,传递给他们

### 回调函数可以返回一个promise对象,该对象的状态和传递的参数可以最终决定then方法返回的promise对象的状态和参数

## Promise.resolve( )

### 参数为非promise对象时

- 返回一个成功的promise对象.该参数就是下一次调用的参数

### 参数为promise对象时

- 状态为失败的promise对象时,最终该resolve方法返回的就是一个失败的promise对象
- 为成功状态的对象时,就是成功状态

## Promise.reject( )

### 参数为非promise对象时

- 会返回一个失败的promise对象

### 参数为成功的promise对象时

- 参数为就算为成功的promise对象时,该方法返回的也是一个失败的promise对象

## Promise.all( arr )

### 传递的参数为一个数组

- 数组里面是每个元素都是promise对象

### 当该数组里面的所有promise对象为成功状态时,该方法返回的就是一个成功的promise对象,该对象调用then方法的参数就是数组值每个promise对象中成功所传递的参数的数组集合

- 可以用来实现加载一些数据,让所有数据加载完成之后,然后在页面进行展示

### 该数组中的promise对象为只要有一个失败状态,最终返回的就是一个失败的promise对象,调用catch方法传递的参数就是最开始失败promise对象所传递的参数

## Promise.race( arr)

### 传递的参数是一个数组,这个数组里面是多个promise对象,

### 返回一个promise对象,该数组里面的promise对象谁最先加载出来,就决定当前方法返回promise对象返回的状态和参数

